sudo: required

language: rust
rust:
  - stable

services:
  - docker

before_install:
  - docker-compose up -d
  - docker ps -a

script:
  - cargo build --verbose
  - RUST_TEST_THREADS=1 cargo test --verbose
